#!/bin/sh /etc/rc.common

START=99
STOP=01
USE_PROCD=1
PROG=/usr/bin/beryl7-agent

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" -config /etc/beryl7/agent.env
    procd_set_param file /etc/beryl7/agent.env
    procd_set_param respawn 3600 5 0
    procd_set_param env GOMEMLIMIT=15MiB GOGC=20
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param oom_score_adj -500
    procd_close_instance
}

stop_service() {
    procd_send_signal "$PROG" 15
}
